# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ade9429888580b3e6e21ef57b09fa9fb1fbac1037585b6ce9aac6cdefbcb03ac45f2003bfb319961f8ee716b1ddfc935e52540bf01cb2f7df2cd8954e40a008

test:
  secret_key_base: 06949ceacb6f6785f20b6747f0419cca880a1c3704c8dbb84c6a371a3f8da66a4f9caf6d9b167de181a9949c685bb5d362620878bbce5a6444e9178e2ee5c975

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
